---
deployment:
    tasks:
        - export DEPLOYPATH=/home/ursabooks/public_html/
        #- /bin/cp -R images $DEPLOYPATH
        #- /bin/cp index.html $DEPLOYPATH
        #- /bin/cp style.css $DEPLOYPATH
